project-leek/project-leek

README.md

- modified readme

---

packages/backend/src/services/nfc-tags/nfc-tag.model.ts
packages/backend/src/services/nfc-tags/nfc-tag.service.ts
packages/commons/src/index.ts
packages/commons/src/nfc-tag.class.ts

add nfc tag model and service

---

packages/backend/test/authentication.test.ts

removes test for local authentication strategy that we don't even implement

---

docs/Definition-of-Done.md

adds Definition of Done

---

packages/app/src/views/Home.vue

this should provide a simple guide. When you pull from master you already have the frame in which you can place your new features.
closes #203

add a simple template which matches the sizes from the figma design

---

packages/app/src/components/uiBlocks/Textfield.vue
packages/app/src/views/Home.vue

212 create a song search field in the home view

---

packages/app/src/components/uiBlocks/Button.vue
packages/app/src/components/uiBlocks/Dropdown.ListItem.ts
packages/app/src/components/uiBlocks/Dropdown.vue
packages/app/src/views/Home.vue
packages/app/src/views/Sandbox.vue

Refactor Dropdown & minor fix TS errors

---

packages/app/src/components/uiBlocks/GroupDropDownItem.vue
packages/app/src/views/Home.vue
packages/backend/src/index.ts
packages/commons/src/nfc-tag.class.ts

should do:
seed nfc tags for debugging
find all groups in nfc tags
make an object which holds groupNames as parent and all it's entries with this group as it's child
v-for over groups
v-for over items

seeding and read new nfc tags groups for home view

---

docs/report/report.tex

Reverts project-leek/project-leek#279

Revert "collect previous retro data into the report"

---

packages/app/src/components/add-tag/AddTagStepPlaceTagOnReader.vue

- fixes broken image
- scales image to frame

308 fix broken image in addTagStepPlaceTagOnReader

---

.env.sample
packages/backend/config/default.json

closes #218 
**IMPORTANT** @anbraten @JanEberlein @tcoro @julianhahn 
You will have to add the JWT_Secret to your .env file:
`JWT_SECRET=[SECRET_GOES_HERE]`

changes location of JWT_Secret from json to .env

---

packages/app/src/components/uiBlocks/Button.vue
packages/app/src/views/NotFound.vue
packages/app/src/views/Welcome.vue

closes #332 
now looks like this:

332 fix welcome-screen login button

---

packages/app/src/components/tag/TagStepTrack.vue

Wait for #360 to be merged first. <- merged :) 
If you already selected a track for your tag, the track selection screen will now automatically reload it if coming back to it.

Load existing track if supplied

---

packages/app/src/components/uiBlocks/GroupDropDownItem.vue
packages/app/src/views/Home.vue
packages/app/src/views/Settings.vue

closes https://github.com/project-leek/project-leek/issues/378
- added gradients to all views
- added a bit of opacity to the background of dropdownItems, so they look nicer with the backgroundgradient

add gradient backgrounds to views

---

packages/app/src/views/Settings.vue
packages/app/src/views/tag/AddTag.vue
packages/app/src/views/tag/TagDetails.vue

exit buttons were really small and hard to hit on mobile.
Also, some tag entry images were really small

Unify tag entry and button sizes

---

packages/app/src/components/uiBlocks/Dropdown.vue

this looks disgusting
now it looks like this:
closes https://github.com/project-leek/project-leek/issues/380

Add margin to dropdown  text

---

packages/app/src/views/Welcome.vue

added corners to welcome screen

---

packages/app/src/views/Home.vue

changes cursor on Tag-Entry to pointer

---

.vscode/settings.json
docs/report/report.tex
packages/app/src/views/Home.vue

376 testing

---

docs/report/report.tex

492 fix images

---

docs/report/report.tex

closes #500 
Neue Struktur:
Bei Vorschlägen zu anderen Titeln gerne melden

500 kapitel einf gen technischer hintergrund oder so

---

docs/report/report.tex

Zu lange Überschriften in Machbarkeitssudie

---

docs/report/report.tex

514 Milestone 6 Abschnitt button refactor

---

docs/report/literature.bib
docs/report/report.tex

Korrektur anhand des Feedbacks einer ultra netten Lektorin 😄

Zweite korrektur
